### ISSUE TITLE
Error during deployment of frontend

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#157]
@sseppi I cannot test the window preview user stories in the "To Review" column, because: <-- see next comment

In addition, the preview shows only the test of the attributes parsed, but not the entire snippet... maybe this is related to the deployed new version of the backend and the old version of the frontend --> see: https://webcomponents.opendatahub.testingmachine.eu/webcomponent/32c2bef1-a691-4b93-bc41-56ecb88e39f0/fullscreen?attribs=Y29udGVudC1pZC1saXN0PSIiO2xhbmd1YWdlPSJkZSI7cGFnZS1zaXplPSIyMCI7ZGVmYXVsdC1wcmVzZW50YXRpb249Imxpc3QiOw%3D%3D

**Comment by Piiit** [comment]
```
+ yarn run test --passWithNoTests
yarn run v1.22.5
$ jest --passWithNoTests
FAIL tests/unit/detail-bottom-bar.spec.js (11.411 s)
  ● Console

    console.error
      [Vue warn]: Error in render: "TypeError: Cannot read property 'configuration' of undefined"
      
      found in
      
      ---> <DetailBottomBar>
             <Root>

      at warn (node_modules/vue/dist/vue.common.dev.js:630:15)
      at logError (node_modules/vue/dist/vue.common.dev.js:1889:5)
      at globalHandleError (node_modules/vue/dist/vue.common.dev.js:1884:3)
      at handleError (node_modules/vue/dist/vue.common.dev.js:1844:5)
      at VueComponent._render (node_modules/vue/dist/vue.common.dev.js:3549:7)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:4063:21)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at new Watcher (node_modules/vue/dist/vue.common.dev.js:4463:12)

    console.error
      TypeError: Cannot read property 'configuration' of undefined
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/src/components/detail-bottom-bar.vue:93:1)
          at Watcher.get (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4474:25)
          at Watcher.evaluate (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4579:21)
          at VueComponent.computedGetter [as attribs] (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4828:17)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/src/components/detail-bottom-bar.vue:110:1)
          at Watcher.get (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4474:25)
          at Watcher.evaluate (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4579:21)
          at Proxy.computedGetter (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4828:17)
          at Proxy.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/src/components/detail-bottom-bar.vue:200:762)
          at VueComponent._render (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:3547:22)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4063:21)
          at Watcher.get (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4474:25)
          at new Watcher (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4463:12)
          at mountComponent (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4070:3)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:9040:10)
          at VueComponent.$mount (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:11940:16)
          at i (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:3121:13)
          at createComponent (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:5969:9)
          at createElm (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:5916:9)
          at VueComponent.__patch__ (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:6466:7)
          at VueComponent._update (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:3942:19)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4063:10)
          at Watcher.get (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4474:25)
          at new Watcher (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4463:12)
          at mountComponent (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4070:3)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:9040:10)
          at VueComponent.$mount (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:11940:16)
          at mount (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/@vue/test-utils/dist/vue-test-utils.js:14062:21)
          at shallowMount (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/@vue/test-utils/dist/vue-test-utils.js:14088:10)
          at Object.<anonymous> (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/tests/unit/detail-bottom-bar.spec.js:33:21)
          at Object.asyncJestTest (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
          at /var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/jest-jasmine2/build/queueRunner.js:45:12
          at new Promise (<anonymous>)
          at mapper (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
          at /var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/jest-jasmine2/build/queueRunner.js:75:41

      at logError (node_modules/vue/dist/vue.common.dev.js:1893:13)
      at globalHandleError (node_modules/vue/dist/vue.common.dev.js:1884:3)
      at handleError (node_modules/vue/dist/vue.common.dev.js:1844:5)
      at VueComponent._render (node_modules/vue/dist/vue.common.dev.js:3549:7)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:4063:21)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at new Watcher (node_modules/vue/dist/vue.common.dev.js:4463:12)
      at mountComponent (node_modules/vue/dist/vue.common.dev.js:4070:3)

    console.error
      [Vue warn]: Error in render: "TypeError: Cannot read property 'configuration' of undefined"
      
      found in
      
      ---> <DetailBottomBar>
             <Root>

      at warn (node_modules/vue/dist/vue.common.dev.js:630:15)
      at logError (node_modules/vue/dist/vue.common.dev.js:1889:5)
      at globalHandleError (node_modules/vue/dist/vue.common.dev.js:1884:3)
      at handleError (node_modules/vue/dist/vue.common.dev.js:1844:5)
      at VueComponent._render (node_modules/vue/dist/vue.common.dev.js:3549:7)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:4063:21)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at new Watcher (node_modules/vue/dist/vue.common.dev.js:4463:12)

    console.error
      TypeError: Cannot read property 'configuration' of undefined
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/src/components/detail-bottom-bar.vue:93:1)
          at Watcher.get (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4474:25)
          at Watcher.evaluate (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4579:21)
          at VueComponent.computedGetter [as attribs] (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4828:17)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/src/components/detail-bottom-bar.vue:110:1)
          at Watcher.get (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4474:25)
          at Watcher.evaluate (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4579:21)
          at Proxy.computedGetter (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4828:17)
          at Proxy.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/src/components/detail-bottom-bar.vue:200:762)
          at VueComponent._render (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:3547:22)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4063:21)
          at Watcher.get (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4474:25)
          at new Watcher (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4463:12)
          at mountComponent (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4070:3)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:9040:10)
          at VueComponent.$mount (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:11940:16)
          at i (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:3121:13)
          at createComponent (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:5969:9)
          at createElm (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:5916:9)
          at VueComponent.__patch__ (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:6466:7)
          at VueComponent._update (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:3942:19)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4063:10)
          at Watcher.get (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4474:25)
          at new Watcher (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4463:12)
          at mountComponent (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:4070:3)
          at VueComponent.call (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:9040:10)
          at VueComponent.$mount (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/vue/dist/vue.common.dev.js:11940:16)
          at mount (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/@vue/test-utils/dist/vue-test-utils.js:14062:21)
          at shallowMount (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/@vue/test-utils/dist/vue-test-utils.js:14088:10)
          at Object.<anonymous> (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/tests/unit/detail-bottom-bar.spec.js:47:21)
          at Object.asyncJestTest (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
          at /var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/jest-jasmine2/build/queueRunner.js:45:12
          at new Promise (<anonymous>)
          at mapper (/var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
          at /var/lib/jenkins/workspace/ontend.test-deploy_development_2/frontend/node_modules/jest-jasmine2/build/queueRunner.js:75:41

      at logError (node_modules/vue/dist/vue.common.dev.js:1893:13)
      at globalHandleError (node_modules/vue/dist/vue.common.dev.js:1884:3)
      at handleError (node_modules/vue/dist/vue.common.dev.js:1844:5)
      at VueComponent._render (node_modules/vue/dist/vue.common.dev.js:3549:7)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:4063:21)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at new Watcher (node_modules/vue/dist/vue.common.dev.js:4463:12)
      at mountComponent (node_modules/vue/dist/vue.common.dev.js:4070:3)

  ● DetailBottomBar › check if popover is not showing

    TypeError: Cannot read property 'configuration' of undefined

      91 |     },
      92 |     attribs() {
    > 93 |       if (!this.$store.state.webcomponent.configuration) {
         | ^
      94 |         return '';
      95 |       }
      96 |

      at VueComponent.call (src/components/detail-bottom-bar.vue:93:1)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at Watcher.evaluate (node_modules/vue/dist/vue.common.dev.js:4579:21)
      at VueComponent.computedGetter [as attribs] (node_modules/vue/dist/vue.common.dev.js:4828:17)
      at VueComponent.call (src/components/detail-bottom-bar.vue:110:1)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at Watcher.evaluate (node_modules/vue/dist/vue.common.dev.js:4579:21)
      at Proxy.computedGetter (node_modules/vue/dist/vue.common.dev.js:4828:17)
      at Proxy.call (src/components/detail-bottom-bar.vue:200:762)
      at VueComponent._render (node_modules/vue/dist/vue.common.dev.js:3547:22)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:4063:21)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at new Watcher (node_modules/vue/dist/vue.common.dev.js:4463:12)
      at mountComponent (node_modules/vue/dist/vue.common.dev.js:4070:3)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:9040:10)
      at VueComponent.$mount (node_modules/vue/dist/vue.common.dev.js:11940:16)
      at i (node_modules/vue/dist/vue.common.dev.js:3121:13)
      at createComponent (node_modules/vue/dist/vue.common.dev.js:5969:9)
      at createElm (node_modules/vue/dist/vue.common.dev.js:5916:9)
      at VueComponent.__patch__ (node_modules/vue/dist/vue.common.dev.js:6466:7)
      at VueComponent._update (node_modules/vue/dist/vue.common.dev.js:3942:19)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:4063:10)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at new Watcher (node_modules/vue/dist/vue.common.dev.js:4463:12)
      at mountComponent (node_modules/vue/dist/vue.common.dev.js:4070:3)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:9040:10)
      at VueComponent.$mount (node_modules/vue/dist/vue.common.dev.js:11940:16)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14062:21)
      at shallowMount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14088:10)
      at Object.<anonymous> (tests/unit/detail-bottom-bar.spec.js:33:21)

  ● DetailBottomBar › check if popover is showing

    TypeError: Cannot read property 'configuration' of undefined

      91 |     },
      92 |     attribs() {
    > 93 |       if (!this.$store.state.webcomponent.configuration) {
         | ^
      94 |         return '';
      95 |       }
      96 |

      at VueComponent.call (src/components/detail-bottom-bar.vue:93:1)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at Watcher.evaluate (node_modules/vue/dist/vue.common.dev.js:4579:21)
      at VueComponent.computedGetter [as attribs] (node_modules/vue/dist/vue.common.dev.js:4828:17)
      at VueComponent.call (src/components/detail-bottom-bar.vue:110:1)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at Watcher.evaluate (node_modules/vue/dist/vue.common.dev.js:4579:21)
      at Proxy.computedGetter (node_modules/vue/dist/vue.common.dev.js:4828:17)
      at Proxy.call (src/components/detail-bottom-bar.vue:200:762)
      at VueComponent._render (node_modules/vue/dist/vue.common.dev.js:3547:22)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:4063:21)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at new Watcher (node_modules/vue/dist/vue.common.dev.js:4463:12)
      at mountComponent (node_modules/vue/dist/vue.common.dev.js:4070:3)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:9040:10)
      at VueComponent.$mount (node_modules/vue/dist/vue.common.dev.js:11940:16)
      at i (node_modules/vue/dist/vue.common.dev.js:3121:13)
      at createComponent (node_modules/vue/dist/vue.common.dev.js:5969:9)
      at createElm (node_modules/vue/dist/vue.common.dev.js:5916:9)
      at VueComponent.__patch__ (node_modules/vue/dist/vue.common.dev.js:6466:7)
      at VueComponent._update (node_modules/vue/dist/vue.common.dev.js:3942:19)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:4063:10)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4474:25)
      at new Watcher (node_modules/vue/dist/vue.common.dev.js:4463:12)
      at mountComponent (node_modules/vue/dist/vue.common.dev.js:4070:3)
      at VueComponent.call (node_modules/vue/dist/vue.common.dev.js:9040:10)
      at VueComponent.$mount (node_modules/vue/dist/vue.common.dev.js:11940:16)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14062:21)
      at shallowMount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14088:10)
      at Object.<anonymous> (tests/unit/detail-bottom-bar.spec.js:47:21)

PASS tests/unit/header.spec.js

Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 failed, 3 passed, 5 total
Snapshots:   0 total
Time:        13.426 s
Ran all test suites.
error Command failed with exit code 1.
```
